import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static const LocalizationsDelegate<AppLocalizations> delegate = _AppLocalizationsDelegate();

  // الخريطة الرئيسية للترجمات
  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      // عام
      'app_name': 'Rehlatna',
      'ok': 'OK',
      'cancel': 'Cancel',
      'save': 'Save',
      'delete': 'Delete',
      'edit': 'Edit',
      'confirm': 'Confirm',
      'close': 'Close',
      'loading': 'Loading...',
      'error': 'Error',
      'success': 'Success',
      'warning': 'Warning',
      'retry': 'Retry',
      'search': 'Search',

      // شاشة الرئيسية
      'home_title': 'Rehlatna',
      'discover_world': 'Discover the world with us',
      'view_all': 'View All',
      'special_offers': 'Special Offers 🔥',
      'group_tours': 'Group Tours 👥',
      'packages': 'Tour Packages 🎒',
      'cruises': 'Sea Cruises Around the World ⚓',
      'educational': 'Educational Trips 📚',
      'visa': 'Visa Services 🛂',

      // 👇 عناوين الأقسام الفرعية
      'turkey_tours': 'Turkey Tours',
      'europe_tours': 'Europe Tours',
      'russia_tours': 'Russia Tours',
      'bosnia_tours': 'Bosnia Tours',
      'georgia_tours': 'Georgia Tours',
      'azerbaijan_tours': 'Azerbaijan Tours',
      'thailand_tours': 'Thailand Tours',
      'vietnam_tours': 'Vietnam Tours',
      'south_korea_tours': 'South Korea Tours',

      // 👇 عناوين الباكدجات
      'western_europe_package': 'Western Europe Package',
      'eastern_europe_package': 'Eastern Europe Package',
      'italy_package': 'Italy Package',
      'spain_package': 'Spain Package',
      'turkey_package': 'Turkey Package',

      // 👇 عناوين الكروزات
      'europe_cruise': 'Europe Cruise',
      'nile_cruise': 'Nile Cruise',
      'sharm_cruise': 'Sharm Cruise',

      // 👇 عناوين الرحلات التعليمية
      'uk_language_courses': 'UK Language Courses',

      // 👇 عناوين التأشيرات
      'schengen_visa': 'Schengen Visa',
      'usa_visa': 'USA Visa',

      // شاشة القسم
      'explore': 'Explore',
      'no_posts': 'No posts yet',
      'pull_to_refresh': 'Pull down to refresh',

      // شاشة الجروبات الجماعية (group_tours_screen)
      'custom_packages': 'Custom Packages',
      'custom_packages_desc': 'Order a custom package for your trip',
      'all_posts': 'All Posts',
      'all_posts_desc': 'View all posts in this section',
      'contact_us_btn': 'Contact Us',
      'browse_now_btn': 'Browse Now',

      // شاشة المنشورات
      'trip_image': 'Trip Image',
      'city': 'City',
      'days': 'days',
      'day': 'day',
      'start_date': 'Start Date',
      'end_date': 'End Date',
      'trip_description': 'Trip Description',
      'call': 'Call',
      'whatsapp': 'WhatsApp',
      'comments': 'Comments',
      'likes': 'Likes',
      'reply': 'Reply',
      'replies': 'Replies',
      'write_comment': 'Write a comment...',
      'write_reply': 'Write a reply...',
      'no_comments': 'No comments yet',
      'be_first_comment': 'Be the first to comment',
      'no_replies': 'No replies yet',
      'be_first_reply': 'Be the first to reply',
      'delete_comment': 'Delete Comment',
      'delete_comment_confirmation': 'Are you sure you want to delete this comment?',
      'delete_reply': 'Delete Reply',
      'delete_reply_confirmation': 'Are you sure you want to delete this reply?',
      'edit_comment': 'Edit Comment',
      'edit_reply': 'Edit Reply',
      'comment_added': 'Comment added successfully',
      'reply_added': 'Reply added successfully',
      'comment_updated': 'Comment updated successfully',
      'reply_updated': 'Reply updated successfully',
      'comment_deleted': 'Comment deleted successfully',
      'reply_deleted': 'Reply deleted successfully',

      // شاشة إضافة/تعديل رحلة
      'add_new_trip': 'Add New Trip',
      'edit_trip': 'Edit Trip',
      'trip_name': 'Trip Name',
      'trip_name_hint': 'e.g. Nowruz Trip',
      'season': 'Season',
      'season_hint': 'e.g. Summer 2024',
      'select_city': 'Select City',
      'start_date_gregorian': '📅 Start Date (Gregorian)',
      'end_date_gregorian': '📅 End Date (Gregorian)',
      'start_date_hijri': '🕌 Start Date (Hijri)',
      'end_date_hijri': '🕌 End Date (Hijri)',
      'day': 'Day',
      'month': 'Month',
      'year': 'Year',
      'trip_description_hint': 'Write trip details here...',
      'select_image': 'Select Trip Image',
      'tap_to_select': 'Tap to select an image from gallery',
      'supports_all_dimensions': 'Supports all dimensions',
      'change_image': 'Change Image',
      'current_image': 'Current Image',
      'image_changed': 'Image changed',
      'save_trip': 'Save Trip',
      'update_trip': 'Update Trip',
      'image_required': 'Please select a trip image',
      'city_required': 'Please select a city',
      'dates_required': 'Please complete all dates',
      'dates_invalid': 'End date must be after start date',

      // شاشة الإعدادات
      'settings': 'Settings',
      'notifications': 'Notifications',
      'notifications_enabled': 'Enabled ✅',
      'notifications_disabled': 'Disabled ❌',
      'notifications_disabled_message': 'Notifications are disabled, you won\'t receive any notifications about new trips',
      'appearance_language': 'Appearance & Language',
      'dark_mode': 'Dark Mode',
      'dark_mode_enabled': 'Enabled 🌙',
      'dark_mode_disabled': 'Disabled ☀️',
      'language': 'Language',
      'support': 'Support',
      'about': 'About',
      'about_description': 'About us and our vision',
      'about_text': 'Rehltna is your perfect platform to discover and book the best tours. We offer a variety of group tours, special offers, cruises, and educational trips.',
      'contact_us': 'Contact Us',
      'contact_description': 'Contact support team',
      'share_app': 'Share App',
      'share_description': 'Share with friends',
      'rate_app': 'Rate App',
      'rate_description': 'Support us with a rating',
      'feedback': 'Feedback',
      'feedback_description': 'Share your suggestions',
      'feedback_hint': 'Write your suggestion or complaint here...',
      'thank_you_feedback': 'Thank you for your feedback!',
      'follow_us': 'Follow Us',
      'company_info': 'Company Info',
      'logout': 'Logout',
      'logout_confirmation': 'Are you sure you want to logout?',
      'logged_out': 'Logged out successfully',
      'version': 'Version 1.0.0',

      // المدن (مختصرة)
      'cairo': 'Cairo',
      'alexandria': 'Alexandria',
      'luxor': 'Luxor',
      'aswan': 'Aswan',
      'sharm_el_sheikh': 'Sharm El Sheikh',
      'hurghada': 'Hurghada',
      'dubai': 'Dubai',
      'abu_dhabi': 'Abu Dhabi',
      'sharjah': 'Sharjah',
      'riyadh': 'Riyadh',
      'jeddah': 'Jeddah',
      'makkah': 'Makkah',
      'madinah': 'Madinah',
      'istanbul': 'Istanbul',
      'antalya': 'Antalya',
      'cappadocia': 'Cappadocia',
      'pamukkale': 'Pamukkale',
      'amman': 'Amman',
      'beirut': 'Beirut',
      'damascus': 'Damascus',
      'baghdad': 'Baghdad',
      'kuwait': 'Kuwait',
      'doha': 'Doha',
      'muscat': 'Muscat',
      'manama': 'Manama',
      'paris': 'Paris',
      'london': 'London',
      'rome': 'Rome',
      'milan': 'Milan',
      'barcelona': 'Barcelona',
      'madrid': 'Madrid',
      'berlin': 'Berlin',
      'munich': 'Munich',
      'vienna': 'Vienna',
      'zurich': 'Zurich',
      'geneva': 'Geneva',
      'amsterdam': 'Amsterdam',
      'brussels': 'Brussels',
      'budapest': 'Budapest',
      'prague': 'Prague',
      'krakow': 'Krakow',
      'athens': 'Athens',
      'lisbon': 'Lisbon',
      'copenhagen': 'Copenhagen',
      'stockholm': 'Stockholm',
      'oslo': 'Oslo',
      'helsinki': 'Helsinki',
      'moscow': 'Moscow',
      'st_petersburg': 'St. Petersburg',
      'new_york': 'New York',
      'los_angeles': 'Los Angeles',
      'san_francisco': 'San Francisco',
      'chicago': 'Chicago',
      'toronto': 'Toronto',
      'vancouver': 'Vancouver',
      'montreal': 'Montreal',
      'mexico_city': 'Mexico City',
      'buenos_aires': 'Buenos Aires',
      'rio': 'Rio de Janeiro',
      'sao_paulo': 'Sao Paulo',
      'tokyo': 'Tokyo',
      'kyoto': 'Kyoto',
      'osaka': 'Osaka',
      'seoul': 'Seoul',
      'beijing': 'Beijing',
      'shanghai': 'Shanghai',
      'hong_kong': 'Hong Kong',
      'bangkok': 'Bangkok',
      'phuket': 'Phuket',
      'chiang_mai': 'Chiang Mai',
      'kuala_lumpur': 'Kuala Lumpur',
      'singapore': 'Singapore',
      'jakarta': 'Jakarta',
      'bali': 'Bali',
      'manila': 'Manila',
      'mumbai': 'Mumbai',
      'delhi': 'Delhi',
      'agra': 'Agra',
      'jaipur': 'Jaipur',
      'cape_town': 'Cape Town',
      'johannesburg': 'Johannesburg',
      'casablanca': 'Casablanca',
      'marrakech': 'Marrakech',
      'fes': 'Fes',
      'tunis': 'Tunis',
      'algiers': 'Algiers',
    },
    'ar': {
      // عام
      'app_name': 'رحلاتنا',
      'ok': 'حسناً',
      'cancel': 'إلغاء',
      'save': 'حفظ',
      'delete': 'حذف',
      'edit': 'تعديل',
      'confirm': 'تأكيد',
      'close': 'إغلاق',
      'loading': 'جاري التحميل...',
      'error': 'خطأ',
      'success': 'تم بنجاح',
      'warning': 'تحذير',
      'retry': 'إعادة المحاولة',
      'search': 'بحث',

      // شاشة الرئيسية
      'home_title': 'رحلاتنا',
      'discover_world': 'اكتشف العالم معنا',
      'view_all': 'عرض الكل',
      'special_offers': 'عروض خاصة 🔥',
      'group_tours': 'قروبات جماعية 👥',
      'packages': 'باكدجات سياحية 🎒',
      'cruises': 'كروزات بحرية حول العالم ⚓',
      'educational': 'رحلات تعليمية 📚',
      'visa': 'خدمات التأشيرات 🛂',

      // 👇 عناوين الأقسام الفرعية
      'turkey_tours': 'رحلات تركيا',
      'europe_tours': 'رحلات أوروبا',
      'russia_tours': 'رحلات روسيا',
      'bosnia_tours': 'رحلات البوسنة',
      'georgia_tours': 'رحلات جورجيا',
      'azerbaijan_tours': 'رحلات اذربيجان',
      'thailand_tours': 'رحلات تايلاند',
      'vietnam_tours': 'رحلات فيتنام',
      'south_korea_tours': 'رحلات كوريا الجنوبية',

      // 👇 عناوين الباكدجات
      'western_europe_package': 'باكدج أوروبا الغربية',
      'eastern_europe_package': 'باكدج أوروبا الشرقية',
      'italy_package': 'باكدج إيطاليا',
      'spain_package': 'باكدج إسبانيا',
      'turkey_package': 'باكدج تركيا',

      // 👇 عناوين الكروزات
      'europe_cruise': 'كروز أوروبا',
      'nile_cruise': 'كروز النيل',
      'sharm_cruise': 'كروز شرم الشيخ',

      // 👇 عناوين الرحلات التعليمية
      'uk_language_courses': 'دورات لغة في بريطانيا',

      // 👇 عناوين التأشيرات
      'schengen_visa': 'تأشيرات شنغن',
      'usa_visa': 'تأشيرات أمريكا',

      // شاشة القسم
      'explore': 'استكشف',
      'no_posts': 'لا توجد منشورات بعد',
      'pull_to_refresh': 'اسحب للأسفل للتحديث',

      // شاشة الجروبات الجماعية (group_tours_screen)
      'custom_packages': 'باكدجات حسب الطلب',
      'custom_packages_desc': 'اطلب باكدج مخصص لرحلتك',
      'all_posts': 'كل المنشورات',
      'all_posts_desc': 'عرض جميع منشورات هذا القسم',
      'contact_us_btn': 'تواصل معنا',
      'browse_now_btn': 'استعرض الآن',

      // شاشة المنشورات
      'trip_image': 'صورة الرحلة',
      'city': 'المدينة',
      'days': 'أيام',
      'day': 'يوم',
      'start_date': 'بداية الرحلة',
      'end_date': 'نهاية الرحلة',
      'trip_description': 'وصف الرحلة',
      'call': 'اتصال',
      'whatsapp': 'واتساب',
      'comments': 'تعليقات',
      'likes': 'إعجابات',
      'reply': 'رد',
      'replies': 'ردود',
      'write_comment': 'اكتب تعليقك...',
      'write_reply': 'اكتب ردك...',
      'no_comments': 'لا توجد تعليقات بعد',
      'be_first_comment': 'كن أول من يعلق',
      'no_replies': 'لا توجد ردود بعد',
      'be_first_reply': 'كن أول من يرد',
      'delete_comment': 'حذف التعليق',
      'delete_comment_confirmation': 'هل أنت متأكد من حذف هذا التعليق؟',
      'delete_reply': 'حذف الرد',
      'delete_reply_confirmation': 'هل أنت متأكد من حذف هذا الرد؟',
      'edit_comment': 'تعديل التعليق',
      'edit_reply': 'تعديل الرد',
      'comment_added': 'تم إضافة التعليق',
      'reply_added': 'تم إضافة الرد',
      'comment_updated': 'تم تعديل التعليق',
      'reply_updated': 'تم تعديل الرد',
      'comment_deleted': 'تم حذف التعليق',
      'reply_deleted': 'تم حذف الرد',

      // شاشة إضافة/تعديل رحلة
      'add_new_trip': 'إضافة رحلة جديدة',
      'edit_trip': 'تعديل الرحلة',
      'trip_name': 'اسم الرحلة',
      'trip_name_hint': 'مثال: رحلة النوروز',
      'season': 'الموسم',
      'season_hint': 'مثال: صيف 2024',
      'select_city': 'اختر المدينة',
      'start_date_gregorian': '📅 تاريخ البدء (ميلادي)',
      'end_date_gregorian': '📅 تاريخ النهاية (ميلادي)',
      'start_date_hijri': '🕌 تاريخ البدء (هجري)',
      'end_date_hijri': '🕌 تاريخ النهاية (هجري)',
      'day': 'يوم',
      'month': 'شهر',
      'year': 'سنة',
      'trip_description_hint': 'اكتب تفاصيل الرحلة هنا...',
      'select_image': 'اختر صورة الرحلة',
      'tap_to_select': 'اضغط لاختيار صورة من المعرض',
      'supports_all_dimensions': 'يدعم جميع الأبعاد',
      'change_image': 'تغيير الصورة',
      'current_image': 'الصورة الحالية',
      'image_changed': 'تم تغيير الصورة',
      'save_trip': 'حفظ الرحلة',
      'update_trip': 'تحديث الرحلة',
      'image_required': 'الرجاء اختيار صورة للرحلة',
      'city_required': 'الرجاء اختيار مدينة',
      'dates_required': 'الرجاء إكمال جميع التواريخ',
      'dates_invalid': 'تاريخ النهاية يجب أن يكون بعد تاريخ البدء',

      // شاشة الإعدادات
      'settings': 'الإعدادات',
      'notifications': 'الإشعارات',
      'notifications_enabled': 'مفعلة ✅',
      'notifications_disabled': 'معطلة ❌',
      'notifications_disabled_message': 'الإشعارات معطلة، لن تصلك أي إشعارات عن الرحلات الجديدة',
      'appearance_language': 'المظهر واللغة',
      'dark_mode': 'الوضع الليلي',
      'dark_mode_enabled': 'مفعل 🌙',
      'dark_mode_disabled': 'معطل ☀️',
      'language': 'اللغة',
      'support': 'الدعم',
      'about': 'عن التطبيق',
      'about_description': 'معلومات عنا ورؤيتنا',
      'about_text': 'تطبيق رحلتنا هو منصتك المثالية لاكتشاف وحجز أفضل الرحلات السياحية. نقدم مجموعة متنوعة من الرحلات الجماعية، العروض الخاصة، الكروزات، والرحلات التعليمية.',
      'contact_us': 'اتصل بنا',
      'contact_description': 'تواصل مع فريق الدعم',
      'share_app': 'شارك التطبيق',
      'share_description': 'أرسل التطبيق لأصدقائك',
      'rate_app': 'قيم التطبيق',
      'rate_description': 'دعمنا بتقييمك على المتجر',
      'feedback': 'رأيك يهمنا',
      'feedback_description': 'شاركنا باقتراحاتك',
      'feedback_hint': 'اكتب اقتراحك أو شكوتك هنا...',
      'thank_you_feedback': 'شكراً لمشاركتنا رأيك!',
      'follow_us': 'تواصل معنا',
      'company_info': 'معلومات الشركة',
      'logout': 'تسجيل الخروج',
      'logout_confirmation': 'هل أنت متأكد من تسجيل الخروج؟',
      'logged_out': 'تم تسجيل الخروج بنجاح',
      'version': 'الإصدار 1.0.0',

      // المدن (مترجمة للعربية)
      'cairo': 'القاهرة',
      'alexandria': 'الإسكندرية',
      'luxor': 'الأقصر',
      'aswan': 'أسوان',
      'sharm_el_sheikh': 'شرم الشيخ',
      'hurghada': 'الغردقة',
      'dubai': 'دبي',
      'abu_dhabi': 'أبوظبي',
      'sharjah': 'الشارقة',
      'riyadh': 'الرياض',
      'jeddah': 'جدة',
      'makkah': 'مكة المكرمة',
      'madinah': 'المدينة المنورة',
      'istanbul': 'اسطنبول',
      'antalya': 'أنطاليا',
      'cappadocia': 'كبادوكيا',
      'pamukkale': 'باموكالي',
      'amman': 'عمان',
      'beirut': 'بيروت',
      'damascus': 'دمشق',
      'baghdad': 'بغداد',
      'kuwait': 'الكويت',
      'doha': 'الدوحة',
      'muscat': 'مسقط',
      'manama': 'المنامة',
      'paris': 'باريس',
      'london': 'لندن',
      'rome': 'روما',
      'milan': 'ميلانو',
      'barcelona': 'برشلونة',
      'madrid': 'مدريد',
      'berlin': 'برلين',
      'munich': 'ميونخ',
      'vienna': 'فيينا',
      'zurich': 'زيورخ',
      'geneva': 'جنيف',
      'amsterdam': 'أمستردام',
      'brussels': 'بروكسل',
      'budapest': 'بودابست',
      'prague': 'براغ',
      'krakow': 'كراكوف',
      'athens': 'أثينا',
      'lisbon': 'لشبونة',
      'copenhagen': 'كوبنهاغن',
      'stockholm': 'ستوكهولم',
      'oslo': 'أوسلو',
      'helsinki': 'هلسنكي',
      'moscow': 'موسكو',
      'st_petersburg': 'سانت بطرسبرغ',
      'new_york': 'نيويورك',
      'los_angeles': 'لوس أنجلوس',
      'san_francisco': 'سان فرانسيسكو',
      'chicago': 'شيكاغو',
      'toronto': 'تورونتو',
      'vancouver': 'فانكوفر',
      'montreal': 'مونتريال',
      'mexico_city': 'مكسيكو سيتي',
      'buenos_aires': 'بوينس آيرس',
      'rio': 'ريو دي جانيرو',
      'sao_paulo': 'ساو باولو',
      'tokyo': 'طوكيو',
      'kyoto': 'كيوتو',
      'osaka': 'أوساكا',
      'seoul': 'سول',
      'beijing': 'بكين',
      'shanghai': 'شنغهاي',
      'hong_kong': 'هونغ كونغ',
      'bangkok': 'بانكوك',
      'phuket': 'بوكيت',
      'chiang_mai': 'تشيانغ ماي',
      'kuala_lumpur': 'كوالالمبور',
      'singapore': 'سنغافورة',
      'jakarta': 'جاكرتا',
      'bali': 'بالي',
      'manila': 'مانيلا',
      'mumbai': 'مومباي',
      'delhi': 'دلهي',
      'agra': 'أغرة',
      'jaipur': 'جايبور',
      'cape_town': 'كيب تاون',
      'johannesburg': 'جوهانسبرغ',
      'casablanca': 'الدار البيضاء',
      'marrakech': 'مراكش',
      'fes': 'فاس',
      'tunis': 'تونس',
      'algiers': 'الجزائر',
    },
  };

  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? _localizedValues['en']?[key] ?? key;
  }
}

// Delegates for localization
class _AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return ['en', 'ar'].contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) {
    return Future.value(AppLocalizations(locale));
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}