// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhlls7thj8vPNmyY8D4zJ4QR6YSRq0n0A',
    appId: '1:51094227945:web:80fe4eb0cb8bf292619978',
    messagingSenderId: '51094227945',
    projectId: 'login-726e6',
    authDomain: 'login-726e6.firebaseapp.com',
    storageBucket: 'login-726e6.firebasestorage.app',
    measurementId: 'G-ZJ9WT3B8HF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmJcu3Lxhh4Q8CDX3Cymx6_aiTZMHlwl0',
    appId: '1:51094227945:android:928e3a13d1ec8bc1619978',
    messagingSenderId: '51094227945',
    projectId: 'login-726e6',
    storageBucket: 'login-726e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbiVbHEGMXQV9PvJ5dejI9cZmkg8tl1rg',
    appId: '1:51094227945:ios:528e52e3fb1c30cf619978',
    messagingSenderId: '51094227945',
    projectId: 'login-726e6',
    storageBucket: 'login-726e6.firebasestorage.app',
    iosClientId: '51094227945-ppkreiil59tt9h6b2qa6gmldo6llkhkd.apps.googleusercontent.com',
    iosBundleId: 'com.example.authAppFixed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbiVbHEGMXQV9PvJ5dejI9cZmkg8tl1rg',
    appId: '1:51094227945:ios:528e52e3fb1c30cf619978',
    messagingSenderId: '51094227945',
    projectId: 'login-726e6',
    storageBucket: 'login-726e6.firebasestorage.app',
    iosClientId: '51094227945-ppkreiil59tt9h6b2qa6gmldo6llkhkd.apps.googleusercontent.com',
    iosBundleId: 'com.example.authAppFixed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhlls7thj8vPNmyY8D4zJ4QR6YSRq0n0A',
    appId: '1:51094227945:web:943373f0b8a94cbc619978',
    messagingSenderId: '51094227945',
    projectId: 'login-726e6',
    authDomain: 'login-726e6.firebaseapp.com',
    storageBucket: 'login-726e6.firebasestorage.app',
    measurementId: 'G-01P1CBF6ST',
  );

}